//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace WindowGameX0
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton runRoutineButton1;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.runRoutineButton1 = new ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.SuspendLayout();
            // 
            // runRoutineButton1
            // 
            this.runRoutineButton1.BackColor = System.Drawing.Color.White;
            this.runRoutineButton1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.runRoutineButton1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.runRoutineButton1.Location = new System.Drawing.Point(30, 52);
            this.runRoutineButton1.Name = "runRoutineButton1";
            this.runRoutineButton1.RoutineToCall = new ABB.Robotics.ScreenMaker.Windows.Forms.RoutineDataObject("T_ROB1", "Module1", "Path_10");
            this.runRoutineButton1.Size = new System.Drawing.Size(82, 70);
            this.runRoutineButton1.Text = "X";
            this.runRoutineButton1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.runRoutineButton1.BeforeRunRoutine += new System.ComponentModel.CancelEventHandler(this.runRoutineButton1_BeforeRunRoutine);
            this.runRoutineButton1.AfterRunRoutine += new System.EventHandler(this.runRoutineButton1_AfterRunRoutine);
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(176, 63);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(174, 105);
            this.tpsLabel1.Title = "tpsLabel1";
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.tpsLabel1);
            this.Controls.Add(this.runRoutineButton1);
            this.Controls.SetChildIndex(this.runRoutineButton1, 0);
            this.Controls.SetChildIndex(this.tpsLabel1, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void runRoutineButton1_BeforeRunRoutine(object sender, System.ComponentModel.CancelEventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["low"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Module1/dxT").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_1 = this.ScreenServices.ApplicationVariables["low"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Module1/dyT").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_1.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in runRoutineButton1_BeforeRunRoutine", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
                e.Cancel = true;
            }
        }
        
        private void runRoutineButton1_AfterRunRoutine(object sender, System.EventArgs e)
        {
            try
            {
                // Calling ApplicationVariableReadWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable read_0 = this.ScreenServices.ApplicationVariables["ULText"];
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["XText"];
                read_0.Value = write_0.Value;
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in runRoutineButton1_AfterRunRoutine", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        #region Protected Methods
        protected override void OnInstall(ABB.Robotics.ScreenMaker.Base.IScreenServices services)
        {
            if ((services.ApplicationVariables.Count == 0))
            {
                // 
                // ULText
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable ULText = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("ULText", "\"\"", typeof(ABB.Robotics.Controllers.RapidDomain.String));
                // 
                // XText
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable XText = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("XText", "\"X\"", typeof(ABB.Robotics.Controllers.RapidDomain.String));
                // 
                // low
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable low = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("low", "-60", typeof(ABB.Robotics.Controllers.RapidDomain.Dnum));
                // 
                // middle
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable middle = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("middle", "0", typeof(ABB.Robotics.Controllers.RapidDomain.Dnum));
                // 
                // high
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable high = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("high", "60", typeof(ABB.Robotics.Controllers.RapidDomain.Dnum));
                // 
                // OText
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable OText = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("OText", "\"O\"", typeof(ABB.Robotics.Controllers.RapidDomain.String));
                // 
                // Store variables
                // 
                services.ApplicationVariables.Add("ULText", ULText);
                services.ApplicationVariables.Add("XText", XText);
                services.ApplicationVariables.Add("low", low);
                services.ApplicationVariables.Add("middle", middle);
                services.ApplicationVariables.Add("high", high);
                services.ApplicationVariables.Add("OText", OText);
            }
            base.OnInstall(services);
        }
        #endregion
    }
}
